### ISSUE TITLE
Install mixup

### ISSUE THREAD

**Issue by timea** [Andrey9kin/digitalocean-cli#1]
Hey Andrey, 

I tried to install your tool, but it seems it used a different version of python for the install then what is actually in my path. Here is what was the output of my install.

![image](https://cloud.githubusercontent.com/assets/4135651/20483484/82309fdc-aff2-11e6-9776-d010f9cb7cfd.png)

When i could see it is no added to my path, I checked this

![image](https://cloud.githubusercontent.com/assets/4135651/20483504/9828af50-aff2-11e6-97e1-44d861c299d1.png)

Then I cd-ed into the folder to use the script directly, then I got this error.

![image](https://cloud.githubusercontent.com/assets/4135651/20483529/af55f3a4-aff2-11e6-8b75-3be5bf5e612f.png)

The python used is: 
Python 2.7.10 (default, Jul 30 2016, 18:31:42) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

If you need any further info, please let me know. :)

**Comment by Andrey9kin** [comment]
@timea Let's see. I do it this way

```
# This will prepare virtual env and pull in all necessary libs
bash prepare_env.sh 

# Activate virtual env; In Windows, it must be something like this - env/Scripts/activate
source env/bin/activate

# Now you are ready to go
pyinstaller --onefile digitalocean-cli.py

# Executable should be in the build dir
dist/digitalocean-cli -h
```

Could you please try as described above? I will update readme
